# Generated by Django 5.2.8 on 2025-12-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('web', 'Sitio Web'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial')], default='web', max_length=20),
        ),
    ]
