# Generated by Django 5.2.8 on 2025-12-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_insumo_color_insumo_marca_producto_imagen_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('proceso', 'En proceso'), ('realizada', 'Realizada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='solicitado', max_length=20),
        ),
    ]
